### PR TITLE
💄 Adding DBA theme

### PR DESCRIPTION
**Pull request by dinsen**
Time to add DBA 🚀 

This PR adds DBA colors and tokens. And of course also add a DBA target to the sample app.

The only thing this PR is missing, is the `GoogleService-Info.plist` file from Firebase.

### CODE REVIEW

**Review by mohsen-schibsted — APPROVED** [review]

**Comment by ChristianTherkelsen** [comment]
Cool stuff @dinsen! 🤓 Where did you find all the required color definitions you added here?

**Comment by dinsen** [comment]
> Cool stuff @dinsen! 🤓 Where did you find all the required color definitions you added here?

Here: https://github.com/warp-ds/warp-ios/blob/main/Sources/Colors/Brands/DBAColors.swift#L3

**Comment by ChristianTherkelsen** [comment]
Ah I didnt notice the link in source. Ill better bookmark that 🙌

**Comment by mohsen-schibsted** [comment]
> Ah I didnt notice the link in source. Ill better bookmark that 🙌

Just a heads up that that Google Doc is manual work and may miss something, our source of truth is always Figma. We are working on using Style Dictionary to automate it and connect Fgima directly to our code.

**Pull request merged**
